name: "stock_analytics"
version: "1.0.0"
profile: "stock_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  stock_analytics:
    staging:
      +materialized: view
      +tags: ["staging"]

seeds:
  stock_analytics:
    raw_jquants_sector_17:
      +column_types:
        S17: string
    raw_jquants_sector_33:
      +column_types:
        S33: string
        S17: string
    raw_jquants_market_segments:
      +column_types:
        Mkt: string
